name: myresume
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5288323804270476
title: Jens Lundberg - Resume
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5
  lightness: 0.9022995743434876
  saturation: 0.9003480314277112
  rhythmicContrast: 0.015098708448931575
purpose: []
